Provider: Yaml

MySql:
  Host: "127.0.0.1"
  Port: "3306"
  User: "root"
  Database: "bansystem"
  Password: "cheesecake"

MongoDB:
  Uri: "URI_LINK"
  Database: "bansystem"

Reasons:
  BanReasons:
    "1":
      Reason: "Hacking"
      Seconds: 287378
    "2":
      Reason: "Bugusing"
      Seconds: 398347
    "3":
      Reason: "Skin/Name"
      Seconds: 937342
    "4":
      Reason: "Insult"
      Seconds: 3893784
    "5":
      Reason: "Teaming"
      Seconds: 8478473
  MuteReasons:
    "1":
      Reason: "Insult"
      Seconds: 287378
    "2":
      Reason: "Advertising"
      Seconds: 398347
    "3":
      Reason: "Spamming"
      Seconds: 937342
    "4":
      Reason: "Caps"
      Seconds: 3893784

WarnSystem:
  EnableBan: false
  MaxWarningCount: 5
  BanReason: "Too many warnings"
  BanSeconds: -1

Settings:
  JoinDelay: 60
  Waterdog: false
  ConfigVersion: 2.0

Commands:
  BanCommand: "ban"
  TempbanCommand: "tempban"
  BanlogCommand: "banlog"
  CheckbanCommand: "checkban"
  ClearbanlogCommand: "clearbanlog"
  EditbanCommand: "editban"
  UnbanCommand: "unban"
  MuteCommand: "mute"
  TempmuteCommand: "tempmute"
  MutelogCommand: "mutelog"
  CheckmuteCommand: "checkmute"
  ClearmutelogCommand: "clearmutelog"
  EditmuteCommand: "editmute"
  UnmuteCommand: "unmute"
  WarnCommand: "warn"
  WarnlogCommand: "warnlog"
  ClearwarningsCommand: "clearwarnlog"
  KickCommand: "kick"
